### ISSUE TITLE
std::cou无法在终端输出内容

### ISSUE THREAD

**Issue by Carl-1999** [ghm0819/laser-line-segment#3]
你好，我在xavier上运行该项目，我的系统版本是ubuntu20，ros为noetic，我在代码中cout一些程序信息，但是终端无法输出。请问这是什么原因？

**Comment by ghm0819** [comment]
> 你好，我在xavier上运行该项目，我的系统版本是ubuntu20，ros为noetic，我在代码中cout一些程序信息，但是终端无法输出。请问这是什么原因？

用launch文件的话，<node name="laserline" pkg="laserline" type="laserline" output=“screen”>

**Comment by ghm0819** [comment]
@Carl-1999 用launch的话，在launch文件修改 node name="laserline" pkg="laserline" type="laserline" output = "screen"

**Comment by Carl-1999** [comment]
@ghm0819 非常感谢您的回答，我忽略了这一点，你的帮助很有用。
